spring:
  datasource:
#    schema: classpath:/feingto-admin.sql
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/feingto-admin?characterEncoding=utf-8
    username: root
    password: root
  event:
    package: com.feing.cloud.admin.listener
  plugin:
    package: com.feing.cloud.admin.plugins
  http:
    web: #Web Upload Path
      resource: #registry.addResourceHandler().addResourceLocations()
        handler: /open
        location: /deploy/resource/
      upload:
        max-file-size: 1024 #上传附件最大值，单位为MB
        file-path: /attachment #附件相对路径
    zipkin:
      base-url: http://${ADMIN_HOST:localhost}:9411/
    rancher:
      base-url: http://${ADMIN_HOST:localhost}:8080/
  mail:
    host: smtp.qq.com
    username: feingto
    password: svsvvpmntohdcaig
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true

management.health.mail.enabled: false

security.oauth2.client:
  client-id: gateway
  client-secret: gateway123456
  grant-type: client_credentials
