spring:
  datasource:
#    schema: classpath:/feing-gateway.sql
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/feing-gateway?characterEncoding=utf-8
    username: root
    password: root
  event:
    package: com.feing.cloud.gateway.listener

security.oauth2:
  resource:
    id: gateway_api
  client:
    client-id: gateway
    client-secret: gateway123456

ribbon:
  connect-timeout: 60000
  read-timeout: 60000
  max-auto-retries: 1
  max-auto-retries-next-server: 1
  eureka.enabled: false #使用eureka注册服务时设为true, consul时设为false

zuul:
#  add-host-header: true
  max-per-route-connections: 100
  max-total-connections: 500
  servlet-path: /file
  ignored-patterns: /, /mgmt/*, /instances, /oauth/**
  ignored-services: '*'
  DebugFilter.pre.disable: true
  flow.limit.client: false # gateway oauth2 client flow limit toggle
  routes:
    uaa-service:
      path: ${authserver.context-path}/**
      service-id: feing-uaa
      strip-prefix: false
      sensitive-headers:
    baidu:
      path: /baidu/**
      url: http://www.baidu.com/
