spring:
  profiles:
    include: init-db-data-user
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/feingto-account?characterEncoding=utf-8
    username: root
    password: root

security.oauth2.client:
  client-id: gateway
  client-secret: gateway123456
  grant-type: client_credentials
