server.port: ${CONFIG_SERVER_PORT:7979}

spring:
  profiles.active: git
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtualHost: /
  security.user.password: ${CONFIG_SERVER_PASSWORD:123456}

management:
  endpoints.web:
    base-path: /mgmt
  endpoint:
    health.show-details: always

logging:
  file: /logs/feingopen/${spring.application.name}_${server.port}.log
  pattern:
    console: '%clr(%d{dd/MM HH:mm:ss}) %clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(-){faint} %m%n'
  level:
    root: INFO
